### ISSUE TITLE
how to adjust batch size?

### ISSUE THREAD

**Issue by shuwenw** [lonePatient/Bert-Multi-Label-Text-Classification#10]
After I changed batch size in basic_config.py from 100 to 32, I got the error ValueError: Target size (torch.Size([32, 36])) must be the same as input size (torch.Size([32, 6])). Did I not adjust it correctly?

**Comment by shuwenw** [comment]
My bad. I just found that even if the batch size is unchanged, I still got this error...

**Comment by lonePatient** [comment]
@shuwenw hi，for kaggle data， target size is （batch_size, 6）
