### ISSUE TITLE
验证集效果准确率 召回率 F值均为0

### ISSUE THREAD

**Issue by angonger** [lonePatient/Bert-Multi-Label-Text-Classification#13]
epoch_metrics 添加ClassReport ，输出结果
                micro avg       0.00      0.00      0.00      5635
               macro avg       0.00      0.00      0.00      5635
            weighted avg       0.00      0.00      0.00      5635
             samples avg       0.00      0.00      0.00      5635
场景是中文多标签分类，找不到是什么问题，求助

**Comment by lonePatient** [comment]
@angonger  你看下 数据格式以及标签是否正确，英文数据集下，我是没有问题的。

**Comment by angonger** [comment]
今天又看了下发现是学习率调的太高的原因，应该是fine-tuning学习率不能太大，采用默认的1e-5即可
