### ISSUE TITLE
ImportError: cannot import name 'PreTrainedBertModel' from 'pytorch_pretrained_bert.modeling' 

### ISSUE THREAD

**Issue by llyiue** [lonePatient/Bert-Multi-Label-Text-Classification#2]
在modeling中找不到PreTrainedBertModel？？

**Comment by tombriles** [comment]
Try changing it to BertPreTrainedModel.

**Comment by lonePatient** [comment]
@llyiue for the new `pytorch-pretrained-bert` package . use comd `from pytorch_pretrained_bert.modeling import BertPreTrainedModel`
