### ISSUE TITLE
Resume training after some epochs 

### ISSUE THREAD

**Issue by alokpadhi** [lonePatient/Bert-Multi-Label-Text-Classification#21]
I was wondering about is there any way to resume the training process. For say, I stopped the training after epoch 2 then will I be able to train from epoch 3 if I re-run the script provided the model still have the past losses available?

**Comment by lonePatient** [comment]
hi @alokpadhi ，if you want to resume the model, you can set `resume_path` parameter,which is your checkpoint model ,and `checkpoint_info.bin` contains training process, such as best metric and epoch, you can add the past losses in `save_info`  75 line  in `train.py` file.  and you can add the past  losses to the `save_info` function in line 75 of the `train.py` file.

**Comment by lonePatient** [comment]
hi @alokpadhi if you want to resume the model, you can set resume_path parameter,which is your checkpoint model ,and checkpoint_info.bin contains training process, such as best metric and epoch, and you can add the past losses to the save_info function in line 75 of the train.py file.

**Comment by alokpadhi** [comment]
Thanks I got it.
