### ISSUE TITLE
MlutiClass Label

### ISSUE THREAD

**Issue by MazenSalama** [lonePatient/Bert-Multi-Label-Text-Classification#30]
Thank you so much for your amazing effort to simplify BERT
i have dataset which has 1, 2, 3 for class column
so i have the id , text, class (1, 2, 3 )
how can i change this inside the code to train on 1,2,3 not 0 ,1 

Thank you

**Comment by lonePatient** [comment]
@MazenSalama hi， You can try https://github.com/lonePatient/BERT-chinese-text-classification-pytorch，it is a multi-class problem
