### ISSUE TITLE
ImportError: cannot import name 'WarmupLinearSchedule' from 'transformers' 

### ISSUE THREAD

**Issue by adiv5** [lonePatient/Bert-Multi-Label-Text-Classification#33]
How to Overcome this error?

**Comment by lonePatient** [comment]
@adiv5 hi
```python
from transformers import AdamW, get_linear_schedule_with_warmup
# line 81
lr_scheduler = get_linear_schedule_with_warmup(optimizer, warmup_steps=warmup_steps, t_total=t_total)
```

**Comment by adiv5** [comment]
> @adiv5 hi
> 
> ```python
> from transformers import AdamW, get_linear_schedule_with_warmup
> # line 81
> lr_scheduler = get_linear_schedule_with_warmup(optimizer, warmup_steps=warmup_steps, t_total=t_total)
> ```

I guess t_total is replaced by `num_training_steps`. Refer to [transformers doc](https://huggingface.co/transformers/main_classes/optimizer_schedules.html?highlight=warmup#transformers.get_linear_schedule_with_warmup)

**Comment by guhur** [comment]
The syntax is:

```python
from transformers import AdamW, get_linear_schedule_with_warmup
# line 81
lr_scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=warmup_steps, num_training_steps=t_total)
```
