### ISSUE TITLE
How should I prepare the input data? 

### ISSUE THREAD

**Issue by ruilinch** [lonePatient/Bert-Multi-Label-Text-Classification#4]
This is a great project. One thing that is unclear is what is the format of the inputs? For BERT, there is a standard format of (training.tsv, dev.tsv). Does this project use the same logic? 
It would be really helpful if there was a working example for reference!

**Comment by desireevl** [comment]
I believe that the only data you need to input is a training csv and a test csv into pybert/dataset/raw, where training has the columns [id, comment_text, labels], where the each label takes an individual column with one hot encoded data. The test csv has the format [id, comment_text].  Please correct me if I'm wrong.
