### ISSUE TITLE
不知道为什么不能使用GPU

### ISSUE THREAD

**Issue by loveJasmine** [lonePatient/Bert-Multi-Label-Text-Classification#9]

**Comment by lonePatient** [comment]
@loveJasmine 您好 ，你看下 config文件里面的n_gpu参数是否正确呢，我是可以使用gpu的

**Comment by loveJasmine** [comment]
初步认为是版本问题
请问你的环境:
cuda
pytorch

**Comment by lonePatient** [comment]
@loveJasmine cuda是9版本  pytorch是1.0  ,我记得1.0跟0,4都是运行的,需要注意的是pytorch_pretrained_bert模块版本问题.

**Comment by loveJasmine** [comment]
我的是cuda8,似乎apex不支持
